__title__ = "mypackage"
__version__ = "0.0.1"
__author__ = "Luis Flores"
__email__ = "luis.flores@gmail.com"
__description__ = "Aplicación Python con MySQL"
__url__ = "https://github.com/Luis89Flores/CRUD_Python_MySQL"
__license__ = "MIT License"